[project]
name = "regional-job-finder"
version = "0.1.0"
description = "CLI tool to search regional jobs using Adzuna API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.2.2",
    "requests>=2.33.1",
]

[tool.uv]
package = true

[project.scripts]
job-finder = "regional_job_finder.main:main"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
